version: '3.8'

services:
  backtest:
    image: tripolskypetr/backtest-kit
    platform: linux/amd64
    # network_mode: host
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: backtest
    ports:
      - "60050:60050"
    restart: unless-stopped
    volumes:
      - ./:/workspace
    working_dir: /workspace
    env_file:
      - .env
    environment:
      - MODE
      - STRATEGY_FILE
      - SYMBOL
      - STRATEGY
      - EXCHANGE
      - FRAME
      - UI
      - TELEGRAM
      - VERBOSE
      - NO_CACHE
      - NO_FLUSH
      - ENTRY
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:60050/api/v1/health/health_check"]
      interval: 30s
      timeout: 10s
      retries: 3
    # command:
    #   - --backtest
    #   - --symbol
    #   - BTCUSDT
    #   - --strategy
    #   - feb_2026_strategy
    #   - --exchange
    #   - ccxt-exchange
    #   - ./content/feb_2026/feb_2026.strategy.ts
    #   - --ui
