import "./config/setup.mjs"

import { run } from 'worker-testbed'

import "./e2e/hold.test.mjs";
import "./e2e/action.test.mjs";
import "./e2e/breakeven.test.mjs";
import "./e2e/cache.test.mjs";
import "./e2e/shutdown.test.mjs";
import "./e2e/markdown.test.mjs";
import "./e2e/partial.test.mjs"
import "./e2e/average.test.mjs"
import "./e2e/dca.test.mjs";
import "./e2e/levels.test.mjs";
import "./e2e/restore.test.mjs";
import "./e2e/persist.test.mjs"
import "./e2e/sequence.test.mjs"
import "./e2e/other.test.mjs"
import "./e2e/defend.test.mjs"
import "./e2e/parallel.test.mjs";
import "./e2e/trailing.test.mjs";
import "./e2e/close.test.mjs"
import "./e2e/sanitize.test.mjs"
import "./e2e/edge.test.mjs"
import "./e2e/timing.test.mjs";
import "./e2e/risk.test.mjs";
import "./e2e/scheduled.test.mjs";
import "./e2e/config.test.mjs";
import "./e2e/columns.test.mjs";
import "./e2e/candle_cache.test.mjs";
import "./e2e/audit.test.mjs";
import "./e2e/gauntlet.test.mjs";
import "./e2e/broker.test.mjs";
import "./e2e/strategy.test.mjs";
import "./e2e/coverage.test.mjs";
import "./e2e/manage.test.mjs";
import "./e2e/recovery.test.mjs";
import "./e2e/short.test.mjs";
import "./e2e/commit.test.mjs";
import "./e2e/hardening.test.mjs";
import "./e2e/stopped.test.mjs";
import "./e2e/live.test.mjs";

import "./spec/audit.test.mjs";
import "./spec/live.test.mjs";
import "./spec/scheduled.test.mjs";
import "./spec/exchange.test.mjs";
import "./spec/risk.test.mjs";
import "./spec/sizing.test.mjs";
import "./spec/heat.test.mjs";
import "./spec/walker.test.mjs";
import "./spec/performance.test.mjs";
import "./spec/list.test.mjs";
import "./spec/callbacks.test.mjs";
import "./spec/report.test.mjs";
import "./spec/event.test.mjs";
import "./spec/validation.test.mjs";
import "./spec/backtest.test.mjs";
import "./spec/pnl.test.mjs";
import "./spec/dca.test.mjs";
import "./spec/config.test.mjs"
import "./spec/candle_cache.test.mjs"
import "./spec/columns.test.mjs"
import "./spec/lookahead.test.mjs";
import "./spec/measure.test.mjs";
import "./spec/measure_walker_unbounded.test.mjs";
import "./spec/measure_storage_keys.test.mjs";
import "./spec/measure_defensive_inputs.test.mjs";
import "./spec/measure_edge_inputs.test.mjs";
import "./spec/measure_empty_state.test.mjs";
import "./spec/measure_lifecycle.test.mjs";
import "./spec/measure_mode_separation.test.mjs";
import "./spec/measure_schedule.test.mjs";
import "./spec/measure_performance.test.mjs";
import "./spec/measure_markdown_rendering.test.mjs";
import "./spec/measure_columns.test.mjs";
import "./spec/measure_infra.test.mjs";
import "./spec/measure_walker.test.mjs";
import "./spec/measure_heat_extras.test.mjs";
import "./spec/measure_schedule_extra.test.mjs";
import "./spec/measure_performance_extra.test.mjs";
import "./spec/measure_event_services.test.mjs";

import "./migration/migrate1.test.mjs"
import "./migration/migrate2.test.mjs"
import "./migration/migrate3.test.mjs"
import "./migration/migrate4.test.mjs";
import "./migration/migrate5.test.mjs";
import "./migration/migrate6.test.mjs";
import "./migration/migrate7.test.mjs";
import "./migration/migrate8.test.mjs";
import "./migration/migrate9.test.mjs";
import "./migration/migrate10.test.mjs";
import "./migration/migrate11.test.mjs";

import "./measure/backtest_1.test.mjs";
import "./measure/backtest_2.test.mjs";
import "./measure/backtest_3.test.mjs";
import "./measure/backtest_4.test.mjs";
import "./measure/backtest_5.test.mjs";
import "./measure/backtest_6.test.mjs";
import "./measure/backtest_7.test.mjs";
import "./measure/backtest_8.test.mjs";
import "./measure/backtest_9.test.mjs";
import "./measure/backtest_10.test.mjs";
import "./measure/backtest_11.test.mjs";
import "./measure/backtest_12.test.mjs";
import "./measure/backtest_13.test.mjs";
import "./measure/backtest_14.test.mjs";
import "./measure/backtest_15.test.mjs";
import "./measure/backtest_16.test.mjs";
import "./measure/backtest_17.test.mjs";
import "./measure/backtest_18.test.mjs";
import "./measure/backtest_19.test.mjs";
import "./measure/backtest_20.test.mjs";
import "./measure/backtest_21.test.mjs";
import "./measure/backtest_22.test.mjs";
import "./measure/backtest_23.test.mjs";
import "./measure/backtest_24.test.mjs";
import "./measure/backtest_25.test.mjs";
import "./measure/backtest_26.test.mjs";
import "./measure/backtest_27.test.mjs";
import "./measure/backtest_28.test.mjs";
import "./measure/backtest_29.test.mjs";
import "./measure/backtest_30.test.mjs";
import "./measure/backtest_31.test.mjs";
import "./measure/backtest_32.test.mjs";
import "./measure/backtest_33.test.mjs";
import "./measure/backtest_34.test.mjs";
import "./measure/backtest_35.test.mjs";
import "./measure/backtest_36.test.mjs";
import "./measure/backtest_37.test.mjs";
import "./measure/backtest_38.test.mjs";
import "./measure/backtest_39.test.mjs";
import "./measure/backtest_40.test.mjs";
import "./measure/backtest_41.test.mjs";
import "./measure/backtest_42.test.mjs";
import "./measure/backtest_43.test.mjs";
import "./measure/backtest_44.test.mjs";
import "./measure/backtest_45.test.mjs";
import "./measure/backtest_46.test.mjs";
import "./measure/backtest_47.test.mjs";
import "./measure/backtest_48.test.mjs";
import "./measure/backtest_49.test.mjs";
import "./measure/backtest_50.test.mjs";
import "./measure/backtest_52.test.mjs";
import "./measure/backtest_53.test.mjs";
import "./measure/backtest_54.test.mjs";
import "./measure/backtest_55.test.mjs";
import "./measure/backtest_56.test.mjs";
import "./measure/backtest_57.test.mjs";
import "./measure/backtest_58.test.mjs";
import "./measure/backtest_59.test.mjs";
import "./measure/backtest_60.test.mjs";
import "./measure/backtest_61.test.mjs";
import "./measure/backtest_62.test.mjs";
import "./measure/backtest_63.test.mjs";
import "./measure/backtest_64.test.mjs";
import "./measure/backtest_65.test.mjs";
import "./measure/backtest_66.test.mjs";
import "./measure/backtest_67.test.mjs";
import "./measure/backtest_68.test.mjs";
import "./measure/backtest_69.test.mjs";
import "./measure/backtest_70.test.mjs";
import "./measure/backtest_71.test.mjs";
import "./measure/backtest_72.test.mjs";
import "./measure/backtest_73.test.mjs";
import "./measure/backtest_74.test.mjs";
import "./measure/backtest_75.test.mjs";
import "./measure/backtest_76.test.mjs";
import "./measure/backtest_77.test.mjs";
import "./measure/backtest_78.test.mjs";
import "./measure/backtest_79.test.mjs";
import "./measure/backtest_80.test.mjs";
import "./measure/backtest_81.test.mjs";
import "./measure/backtest_82.test.mjs";
import "./measure/backtest_83.test.mjs";
import "./measure/backtest_84.test.mjs";
import "./measure/backtest_85.test.mjs";
import "./measure/backtest_86.test.mjs";
import "./measure/backtest_87.test.mjs";
import "./measure/backtest_88.test.mjs";
import "./measure/backtest_89.test.mjs";
import "./measure/backtest_90.test.mjs";
import "./measure/backtest_91.test.mjs";
import "./measure/backtest_92.test.mjs";
import "./measure/backtest_93.test.mjs";
import "./measure/backtest_94.test.mjs";
import "./measure/backtest_95.test.mjs";
import "./measure/backtest_96.test.mjs";
import "./measure/backtest_97.test.mjs";
import "./measure/backtest_98.test.mjs";
import "./measure/backtest_99.test.mjs";
import "./measure/backtest_100.test.mjs";

run(import.meta.url, () => {
    console.log("All tests are finished");
    // Give tape a beat to finalize the LAST test record: an immediate exit
    // races its onEnd tick and reports "test exited without ending"
    setTimeout(() => process.exit(-1), 250);
});
