@startyaml
exchangeGlobalService:
	• exchangeGlobalService: ""
	loggerService:
		• loggerService: ""
		methodContextService: ""
		executionContextService: ""
	exchangeConnectionService:
		• exchangeConnectionService: ""
		loggerService:
			• loggerService: ""
			methodContextService: ""
			executionContextService: ""
		executionContextService: ""
		exchangeSchemaService:
			• exchangeSchemaService: ""
			loggerService:
				• loggerService: ""
				methodContextService: ""
				executionContextService: ""
		methodContextService: ""
strategyGlobalService:
	• strategyGlobalService: ""
	loggerService:
		• loggerService: ""
		methodContextService: ""
		executionContextService: ""
	strategyConnectionService:
		• strategyConnectionService: ""
		loggerService:
			• loggerService: ""
			methodContextService: ""
			executionContextService: ""
		executionContextService: ""
		strategySchemaService:
			• strategySchemaService: ""
			loggerService:
				• loggerService: ""
				methodContextService: ""
				executionContextService: ""
		exchangeConnectionService:
			• exchangeConnectionService: ""
			loggerService:
				• loggerService: ""
				methodContextService: ""
				executionContextService: ""
			executionContextService: ""
			exchangeSchemaService:
				• exchangeSchemaService: ""
				loggerService:
					• loggerService: ""
					methodContextService: ""
					executionContextService: ""
			methodContextService: ""
		methodContextService: ""
frameGlobalService:
	• frameGlobalService: ""
	loggerService:
		• loggerService: ""
		methodContextService: ""
		executionContextService: ""
	frameConnectionService:
		• frameConnectionService: ""
		loggerService:
			• loggerService: ""
			methodContextService: ""
			executionContextService: ""
		frameSchemaService:
			• frameSchemaService: ""
			loggerService:
				• loggerService: ""
				methodContextService: ""
				executionContextService: ""
		methodContextService: ""
liveGlobalService:
	• liveGlobalService: ""
	loggerService:
		• loggerService: ""
		methodContextService: ""
		executionContextService: ""
	liveLogicPublicService:
		• liveLogicPublicService: ""
		loggerService:
			• loggerService: ""
			methodContextService: ""
			executionContextService: ""
		liveLogicPrivateService:
			• liveLogicPrivateService: ""
			loggerService:
				• loggerService: ""
				methodContextService: ""
				executionContextService: ""
			strategyGlobalService:
				• strategyGlobalService: ""
				loggerService:
					• loggerService: ""
					methodContextService: ""
					executionContextService: ""
				strategyConnectionService:
					• strategyConnectionService: ""
					loggerService:
						• loggerService: ""
						methodContextService: ""
						executionContextService: ""
					executionContextService: ""
					strategySchemaService:
						• strategySchemaService: ""
						loggerService:
							• loggerService: ""
							methodContextService: ""
							executionContextService: ""
					exchangeConnectionService:
						• exchangeConnectionService: ""
						loggerService:
							• loggerService: ""
							methodContextService: ""
							executionContextService: ""
						executionContextService: ""
						exchangeSchemaService:
							• exchangeSchemaService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
						methodContextService: ""
					methodContextService: ""
	strategyValidationService:
		• strategyValidationService: ""
		loggerService:
			• loggerService: ""
			methodContextService: ""
			executionContextService: ""
	exchangeValidationService:
		• exchangeValidationService: ""
		loggerService:
			• loggerService: ""
			methodContextService: ""
			executionContextService: ""
backtestGlobalService:
	• backtestGlobalService: ""
	loggerService:
		• loggerService: ""
		methodContextService: ""
		executionContextService: ""
	backtestLogicPublicService:
		• backtestLogicPublicService: ""
		loggerService:
			• loggerService: ""
			methodContextService: ""
			executionContextService: ""
		backtestLogicPrivateService:
			• backtestLogicPrivateService: ""
			loggerService:
				• loggerService: ""
				methodContextService: ""
				executionContextService: ""
			strategyGlobalService:
				• strategyGlobalService: ""
				loggerService:
					• loggerService: ""
					methodContextService: ""
					executionContextService: ""
				strategyConnectionService:
					• strategyConnectionService: ""
					loggerService:
						• loggerService: ""
						methodContextService: ""
						executionContextService: ""
					executionContextService: ""
					strategySchemaService:
						• strategySchemaService: ""
						loggerService:
							• loggerService: ""
							methodContextService: ""
							executionContextService: ""
					exchangeConnectionService:
						• exchangeConnectionService: ""
						loggerService:
							• loggerService: ""
							methodContextService: ""
							executionContextService: ""
						executionContextService: ""
						exchangeSchemaService:
							• exchangeSchemaService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
						methodContextService: ""
					methodContextService: ""
			exchangeGlobalService:
				• exchangeGlobalService: ""
				loggerService:
					• loggerService: ""
					methodContextService: ""
					executionContextService: ""
				exchangeConnectionService:
					• exchangeConnectionService: ""
					loggerService:
						• loggerService: ""
						methodContextService: ""
						executionContextService: ""
					executionContextService: ""
					exchangeSchemaService:
						• exchangeSchemaService: ""
						loggerService:
							• loggerService: ""
							methodContextService: ""
							executionContextService: ""
					methodContextService: ""
			frameGlobalService:
				• frameGlobalService: ""
				loggerService:
					• loggerService: ""
					methodContextService: ""
					executionContextService: ""
				frameConnectionService:
					• frameConnectionService: ""
					loggerService:
						• loggerService: ""
						methodContextService: ""
						executionContextService: ""
					frameSchemaService:
						• frameSchemaService: ""
						loggerService:
							• loggerService: ""
							methodContextService: ""
							executionContextService: ""
					methodContextService: ""
	strategyValidationService:
		• strategyValidationService: ""
		loggerService:
			• loggerService: ""
			methodContextService: ""
			executionContextService: ""
	exchangeValidationService:
		• exchangeValidationService: ""
		loggerService:
			• loggerService: ""
			methodContextService: ""
			executionContextService: ""
	frameValidationService:
		• frameValidationService: ""
		loggerService:
			• loggerService: ""
			methodContextService: ""
			executionContextService: ""
@endyaml